# -*- coding: utf-8 -*-
"""House  price predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-OpYqWadpBan1JgGgec_18ibTLx-zNm
"""

# House Price Prediction Project
# Importing necessary libraries
import pandas as pd # table form
import numpy as np # numercial calculation
import matplotlib.pyplot as plt # visualization
import seaborn as sns
from sklearn.model_selection import train_test_split # ML model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Load the California Housing dataset
from sklearn.datasets import fetch_california_housing
data = fetch_california_housing()
df = pd.DataFrame(data.data, columns=data.feature_names) # covert the data into pandas dataform
df['PRICE'] = data.target * 100000  # Convert to actual dollar amounts

# Display first 5 rows
print("First 5 rows of the dataset:")
display(df.head())

# Basic information about the dataset
print("\nDataset Information:")
print(df.info())

# Statistical summary
print("\nStatistical Summary:")
display(df.describe())

# Visualizing the distribution of house prices
plt.figure(figsize=(10, 6))
sns.histplot(df['PRICE'], bins=30, kde=True)
plt.title('Distribution of House Prices')
plt.xlabel('Price ($)')
plt.show()

# Correlation matrix
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt='.2f')# diff feature relation
plt.title('Correlation Matrix')
plt.tight_layout()
plt.show()

# Visualize relationships with price
plt.figure(figsize=(15, 10))
for i, col in enumerate(data.feature_names, 1):
    plt.subplot(3, 3, i)
    sns.scatterplot(x=df[col], y=df['PRICE'], alpha=0.5) # relation betwwen two virables
    plt.title(f'{col} vs Price')
    plt.tight_layout()
plt.show()

# Prepare the data
X = df.drop('PRICE', axis=1)
y = df['PRICE']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # divided the data two part ,used to tech the model , how the modle is good

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)#The model learns the relationship between house features and prices

# Make predictions
y_pred = model.predict(X_test)# x acutal and y predicted price

# Model evaluation
print("\nModel Evaluation:")
print("-----------------")
print(f"Mean Squared Error: ${mean_squared_error(y_test, y_pred):,.2f}")
print(f"Root Mean Squared Error: ${np.sqrt(mean_squared_error(y_test, y_pred)):,.2f}")
print(f"R-squared Score: {r2_score(y_test, y_pred):.4f}")

# Feature importance
feature_importance = pd.DataFrame({ # which feature price is important
    'Feature': X.columns,
    'Importance': abs(model.coef_)
}).sort_values('Importance', ascending=False)

print("\nFeature Importance:")
display(feature_importance)

# Plotting feature importance
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance) # visulization bar plot
plt.title('Feature Importance in Price Prediction')
plt.tight_layout()
plt.show()

# Making a prediction on new data (example)
print("\nExample Prediction:")
print("-------------------")
# Features in order: MedInc, HouseAge, AveRooms, AveBedrms, Population, AveOccup, Latitude, Longitude
example_house = {
'MedInc': [8.3252],        # Median income in block group
    'HouseAge': [41.0],        # House age
    'AveRooms': [6.98],        # Average number of rooms
    'AveBedrms': [1.02],       # Average number of bedrooms
    'Population': [322.0],     # Block group population
    'AveOccup': [2.56],        # Average house occupancy
    'Latitude': [37.88],       # Latitude
    'Longitude': [-122.23]     # Longitude
}


# Create DataFrame for the new house
new_house = pd.DataFrame(example_house)

# Make prediction
predicted_price = model.predict(new_house)

# Display the prediction
print("\nHouse Features:")
for feature, value in example_house.items():
    print(f"{feature}: {value[0]}")

print(f"\nPredicted Price: ${predicted_price[0]:,.2f}")

# Compare with actual statistics
print("\nPrice Statistics in the Dataset:")
print(f"Minimum Price: ${df['PRICE'].min():,.2f}")
print(f"Average Price: ${df['PRICE'].mean():,.2f}")
print(f"Maximum Price: ${df['PRICE'].max():,.2f}")

simple_house = {
    'Bedrooms': [3],         # Number of bedrooms (1-5)
    'Bathrooms': [2],        # Number of bathrooms (1-4)
    'Area (sqft)': [1500],   # Size of house (500-5000 sq ft)
    'Floors': [2],           # Number of floors (1-3)
    'Year Built': [2010]     # Year house was built (1950-2023)
}

